# Generated by Django 3.2 on 2021-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosier',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
