# Generated by Django 3.2 on 2021-04-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_dossier_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
