# Generated by Django 3.2 on 2021-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
