# Generated by Django 3.2 on 2021-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Death active', 'Death active')], default='Active', max_length=20)),
                ('document_root', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Secret', 'Secret'), ('Top-Secret', 'Top-Secret')], max_length=50)),
            ],
        ),
    ]
